import Nav from "./components/Nav.jsx";
import Dashboard from "./components/Dashboard.jsx";
import History from "./components/History.jsx";
import ProjectView from "./components/ProjectView.jsx";
import Pricing from "./components/Pricing.jsx"
import Landing from "./components/Landing.jsx";
import { Routes, Route } from "react-router-dom";
import Legal from './components/Legal.jsx'
import About from "./components/Aboutme.jsx";

function App() {
  return (
    <div>
      <Routes>
        <Route path="/" element={<Landing />} />
        <Route path="/dashboard" element={<Dashboard />} />
        <Route path="/history" element={<History/>}/>
        <Route path="/pricing" element={<Pricing />} />
        {/* Fixed: Matched the element to your 'About' import name */}
        <Route path="/about" element={<About />} />
        
        <Route path="/terms" element={
          <Legal 
            title="Terms of Service" 
            lastUpdated="June 2026"
            content={`1. Acceptance of Terms
By accessing and using FlowState, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use our service.

2. Description of Service
FlowState provides an AI-powered content analysis tool that processes user-provided video links to extract audio transcripts and visual frames, ultimately generating text-based content. FlowState does not generate, edit, or host video files.

3. Account Registration & Security
To use FlowState, you must register for an account using a valid email address or third-party authentication (e.g., Google). You are entirely responsible for maintaining the confidentiality of your account credentials and for any activity that occurs under your account.

4. Credits and Payments
FlowState operates on a one-time, pay-as-you-go credit system. 
- You must purchase digital "credits" to perform AI generations. 
- All payments are processed securely through our third-party payment gateway (Razorpay). 
- We do not store your credit card information. 
- Credits do not expire, but they have no real-world cash value and are strictly non-refundable. There are no recurring subscription fees.

5. User Conduct and Acceptable Use
You agree to use FlowState only for lawful purposes. You are strictly prohibited from submitting video links or generating content that:
- Promotes illegal acts, violence, or self-harm.
- Contains explicit, pornographic, or highly offensive material.
- Infringes upon the intellectual property rights, copyright, or privacy of others.
We reserve the right to suspend or terminate any account found violating these rules without refund.

6. Intellectual Property
You retain all rights to the video links you provide and the text output generated by your prompts. However, you must ensure you have the legal right to process the videos you submit to our AI. FlowState makes no claims of ownership over your input data or the resulting generated text.

7. Third-Party Services
FlowState utilizes third-party artificial intelligence APIs to process transcripts and generate text. We do not guarantee the absolute accuracy, reliability, or appropriateness of the AI-generated text. The output is provided "as is," and you are responsible for reviewing it before use.

8. Limitation of Liability
To the maximum extent permitted by law, FlowState and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service.

9. Changes to These Terms
We reserve the right to modify these terms at any time. We will notify users of any significant changes by updating the "Last updated" date at the top of this page. Your continued use of FlowState after such modifications constitutes your acknowledgment and acceptance of the updated terms.`}
          />
        } />

        <Route path="/privacy" element={
          <Legal 
            title="Privacy Policy" 
            lastUpdated="June 2026"
            content={`1. Information We Collect
We collect your email address and basic profile information when you register via Supabase. 

2. Media Processing & Data Security
When you provide a video link, we temporarily process it to extract audio and frames for AI analysis. These files are immediately and permanently deleted from our servers the moment the text generation is complete. We do not store your media.

3. Third-Party Services
We use secure third-party AI providers to process your text and transcripts. Payment processing is handled entirely by Razorpay; we never see or store your credit card details.`}
          />
        } />

        <Route path="/refunds" element={
          <Legal 
            title="Refund Policy" 
            lastUpdated="June 2026"
            content={`1. Strict No Refund Policy
FlowState operates on a one-time, pay-as-you-go digital credit system. Because we incur irreversible costs from our AI providers the moment credits are added to your account, all sales are strictly final.

2. Non-Refundable Scenarios
We do not offer refunds, partial or in full, for:
- Unused credits remaining in your account.
- Accidental or duplicate purchases.
- Dissatisfaction with the exact wording of the AI-generated text.
- Account termination due to a violation of our Terms of Service.

3. One-Time Purchases (No Subscriptions)
FlowState does not have recurring subscriptions. All credit packs are one-time purchases. You will never be automatically charged or billed on a recurring basis. Because there is no subscription, there is nothing you need to formally "cancel"—you simply buy credits when you need them, and stop when you don't. Your remaining credits will stay in your account forever.`}
          />
        } />

      </Routes>
    </div>
  );
}

export default App;